#!/usr/bin/env python3
"""
manifest_generator.py -- turn recommendations into a YAML patch a human can review.

A fluent builder, because the output is a document assembled from optional parts (resources, an
HPA target co-change, annotations recording provenance) and a builder keeps the assembly readable
without a constructor taking nine arguments.

Two rules the generator enforces structurally, so they cannot be forgotten at a call site:

  * memory limit == memory request, always. Predictable allocation, bottom of the eviction order,
    no accidental QoS demotion.
  * A resource change and its HPA target change appear in the SAME document. Shipping them
    separately means the cluster spends time in the intermediate state, and the intermediate state
    is the outage: lower request + unchanged target = utilisation-of-request jumps = scale-out.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime

from .recommendation_engine import Action, ResourceRecommendation


def _fmt_cpu(cores: float) -> str:
    """Millicores below 10 cores; whole cores above. Matches how operators write these by hand."""
    millicores = int(round(cores * 1000))
    if millicores % 1000 == 0 and millicores >= 1000:
        return f"{millicores // 1000}"
    return f"{millicores}m"


def _fmt_memory(mib: float) -> str:
    mib_i = int(round(mib))
    if mib_i % 1024 == 0 and mib_i >= 1024:
        return f"{mib_i // 1024}Gi"
    return f"{mib_i}Mi"


@dataclass
class ContainerPatch:
    container: str
    cpu_request: str | None = None
    cpu_limit: str | None = None
    memory_request: str | None = None
    memory_limit: str | None = None
    notes: list[str] = field(default_factory=list)


class ManifestBuilder:
    """Fluent builder for a single workload's resource patch."""

    def __init__(self, namespace: str, workload: str, kind: str = "Deployment") -> None:
        self.namespace = namespace
        self.workload = workload
        self.kind = kind
        self._containers: dict[str, ContainerPatch] = {}
        self._hpa_target: int | None = None
        self._hpa_note: str | None = None
        self._evidence: list[str] = []
        self._run_id: str | None = None

    def with_recommendation(self, rec: ResourceRecommendation) -> ManifestBuilder:
        if rec.action in (Action.KEEP, Action.NEEDS_REVIEW):
            # Nothing to patch. needs_review belongs in the PR body as a note, not in the manifest.
            self._evidence.append(
                f"{rec.container}/{rec.resource}: {rec.action} -- {rec.rationale}"
            )
            return self

        patch = self._containers.setdefault(rec.container, ContainerPatch(container=rec.container))
        if rec.resource == "cpu":
            patch.cpu_request = _fmt_cpu(rec.recommended_request)
            patch.cpu_limit = _fmt_cpu(rec.recommended_limit)
        else:
            mem = _fmt_memory(rec.recommended_request)
            # Structurally enforced: both sides get the same value.
            patch.memory_request = mem
            patch.memory_limit = mem

        patch.notes.append(
            f"{rec.resource}: bound by {rec.binding_constraint}, basis {rec.sizing_basis}, "
            f"evidence {rec.evidence_tier}"
        )
        self._evidence.append(
            f"{rec.container}/{rec.resource}: {rec.action} "
            f"{rec.current_request} -> {rec.recommended_request} "
            f"({rec.binding_constraint}, {rec.evidence_tier}, {rec.confidence} confidence)"
        )
        return self

    def with_hpa_target(self, target_pct: int, note: str) -> ManifestBuilder:
        """Co-change the HPA target IN THIS PATCH. Never as a follow-up PR."""
        self._hpa_target = target_pct
        self._hpa_note = note
        return self

    def with_run_id(self, run_id: str) -> ManifestBuilder:
        self._run_id = run_id
        return self

    def build(self) -> str:
        if not self._containers and self._hpa_target is None:
            return ""

        stamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
        lines: list[str] = [
            f"# Generated by KubeThrifty at {stamp}",
            "#",
            "# Review before merging. KubeThrifty opens PRs; it does not merge them, and it never",
            "# applies resource changes directly to a cluster.",
            "#",
        ]
        for e in self._evidence:
            lines.append(f"#   {e}")
        lines += [
            "---",
            "apiVersion: apps/v1",
            f"kind: {self.kind}",
            "metadata:",
            f"  name: {self.workload}",
            f"  namespace: {self.namespace}",
            "  annotations:",
            f'    kubethrifty.io/sized-at: "{stamp}"',
        ]
        if self._run_id:
            lines.append(f'    kubethrifty.io/run-id: "{self._run_id}"')
        lines += [
            "spec:",
            "  template:",
            "    spec:",
            "      containers:",
        ]
        for patch in self._containers.values():
            lines.append(f"        - name: {patch.container}")
            lines.append("          resources:")
            if patch.cpu_request or patch.memory_request:
                lines.append("            requests:")
                if patch.cpu_request:
                    lines.append(f"              cpu: {patch.cpu_request}")
                if patch.memory_request:
                    lines.append(f"              memory: {patch.memory_request}")
            if patch.cpu_limit or patch.memory_limit:
                lines.append("            limits:")
                if patch.cpu_limit:
                    lines.append(f"              cpu: {patch.cpu_limit}")
                if patch.memory_limit:
                    # limit == request for memory. Stated in the output so a reviewer sees the rule.
                    lines.append(f"              memory: {patch.memory_limit}  # == request")

        if self._hpa_target is not None:
            lines += [
                "---",
                "# Co-changed in the SAME patch, deliberately. A lower request raises",
                "# utilisation-of-request for identical traffic, so leaving the old target in place",
                "# would make the HPA scale out and turn this saving into a larger bill.",
                f"# {self._hpa_note}",
                "apiVersion: autoscaling/v2",
                "kind: HorizontalPodAutoscaler",
                "metadata:",
                f"  name: {self.workload}",
                f"  namespace: {self.namespace}",
                "spec:",
                "  metrics:",
                "    - type: Resource",
                "      resource:",
                "        name: cpu",
                "        target:",
                "          type: Utilization",
                f"          averageUtilization: {self._hpa_target}",
            ]

        return "\n".join(lines) + "\n"
